// Writes AGENTS.md: the guide for agents (Claude, Sol, …) painting with or
// working on the simulator, built from the same tables the page uses
// (src/actions.js, src/params.js, src/knob-docs.js, src/brushes.js,
// src/paper.js), so it stays true. Run after changing any of them:
//   node tools/agents-doc.mjs
import { writeFile } from 'node:fs/promises';
import { TOOLS, ACTIONS, STUDIO, KEYS, SCRIPT_API } from '../src/actions.js';
import { PARAMS } from '../src/params.js';
import { KNOB_DOCS } from '../src/knob-docs.js';
import { BRUSHES } from '../src/brushes.js';

const esc = s => String(s).replace(/\|/g, '\\|');
const out = [];
out.push(`# Agents' guide

Generated by \`node tools/agents-doc.mjs\` from the page's own tables; edit those, not this file.

Hyperreal Watercolor is a physically based watercolour simulator (WebGPU, plain JS). A painter uses it by hand; agents paint with scripts and work on the physics. Both reach the same tools and actions by the same names. The painter's observations outrank estimated data. Run the probes before and after any physics change.

## Running

- \`python3 tools/serve.py\` serves the app at http://127.0.0.1:8765/ (no cache).
- \`node tools/paint.mjs paintings/x.js [--shot out.png] [--save out.wcpaint] [--open in.wcpaint] [--looks dir] [--replay strokes.json]\` runs a painting script in a private headless Chrome. See \`paintings/\` for examples.
- \`node tools/measure.mjs [probe ...] [--set knob=value] [--shot out.png]\` runs the calibration probes (\`tools/probes.js\`). The \`api\` probe checks that everything in this guide exists.
- \`node tools/ui-shot.mjs out.png ['js']\` screenshots the whole page, panel included.
- Paint in your own headless page (paint.mjs, measure.mjs), not the painter's tab. Never reload their tab without asking: the paint state lives on the GPU. Don't trigger downloads (the save actions) on their machine.

## A painting script

\`\`\`js
const S = window.__sim, h = S.headless, V = S.values, M = window.__minds;
window.__paintDone = (async () => {
  h.setPaper('coldPress', 1); h.setTone('natural'); S.clear();
  h.setBrushPreset('mop'); V.dipLoad = 1;
  h.setBrush([['French Ultramarine', 2], ['Transparent Red Oxide', 1]]); V.brushPigment = 0.2;
  S.tool('paint');
  await S.path([[0, 100, 1], [1024, 120, 1]], 2);
  await M.waitDry([[500, 110]]);
  await S.look('sky');
})();
\`\`\`
`);

out.push('## Tools\n\n`sim.tool(name)`, or the key.\n\n| name | key | what it does |\n|---|---|---|');
for (const t of TOOLS) out.push(`| \`${t.name}\` | ${t.key} | ${esc(t.doc)} |`);
out.push('\n## Actions\n\n`sim.act(name, ...args)`, or the button. *Human only* means a script does it another way (named in the text).\n\n| name | key | what it does |\n|---|---|---|');
for (const a of ACTIONS) out.push(`| \`${a.name}\`${a.hold ? ' (held: on/off)' : ''} | ${a.key ?? ''} | ${a.human ? '*Human only.* ' : ''}${esc(a.doc)} |`);
out.push('\nOther keys: ' + KEYS.map(([k, w]) => `${k} ${w}`).join(' · ') + '.');

for (const e of SCRIPT_API) {
  if (e.section) { out.push(`\n## ${e.section}\n`); continue; }
  out.push(`- \`${e.call}\`: ${e.doc}`);
}

out.push(`\n## Brushes\n\n\`sim.headless.setBrushPreset(key)\`.\n`);
for (const [k, b] of Object.entries(BRUSHES)) out.push(`- \`${k}\`: ${b.name} (${b.type === 'water' ? 'water brush: keeps pigment and water between strokes' : 'dip brush: reloads every stroke'})`);

out.push('\n## Knobs\n\nAll in `sim.values` by key. The page shows the studio ones always, the brush and paper ones under *Build*, and the rest in the lab, which is hidden until the painter asks for it. Number boxes and `sim.values` are unclamped.');
out.push('\n### Studio (always in view)\n\n| key | label | what it does |\n|---|---|---|');
for (const k of STUDIO) out.push(`| \`${k.key}\` | ${k.label} | ${esc(k.doc)} |`);
const studio = new Set(STUDIO.map(k => k.key));
const groups = {};
for (const p of PARAMS) if (!studio.has(p.key)) (groups[KNOB_DOCS[p.key]?.tier === 'dev' ? 'Performance and debugging' : p.group] ??= []).push(p);
for (const [g, ps] of Object.entries(groups)) {
  out.push(`\n### ${g}\n\n| key | default | label | what it does |\n|---|---|---|---|`);
  for (const p of ps) out.push(`| \`${p.key}\` | ${p.v} | ${esc(p.label ?? p.key)} | ${esc(KNOB_DOCS[p.key]?.doc ?? '')} |`);
}
await writeFile(new URL('../AGENTS.md', import.meta.url), out.join('\n') + '\n');
console.error('wrote AGENTS.md');
