// Builds src/spectra-data.js from the measured spectra in notes/spectra
// (the private notes repo; see notes/spectra/sources.md): for each pan with data, a masstone and a
// tint reflectance spectrum resampled to the renderer's 16 bands
// (400-700 nm, each band the mean of the source over +-10 nm). Tints are
// the lightest available: darker ones saturate where the pigment absorbs,
// which exaggerates its absorption shape.
//
//   node tools/spectra.mjs
//
// All sources are acrylic paints, not watercolour: their absorption
// (where along the spectrum each pigment absorbs) carries over; their
// scattering and levels don't, so pigments.js uses these as the shape of
// the spectrum and matches the colour to the painter's swatches.

import { readFile, writeFile } from 'node:fs/promises';

const DIR = new URL('../notes/spectra/', import.meta.url);
const BANDS = Array.from({ length: 16 }, (_, k) => 400 + 20 * k);

// Pan name -> [masstone file, tint file or null, note].
const PICK = {
  'Phthalo Green': ['PG7_masstone_Berns2016', 'PG7_tint010_RIT-Okumura', 'Golden acrylic'],
  // Process cyan (ISO 2846, PB15:3) printed solid on coated paper, divided
  // by the bare paper: the film's own filtering, like a glaze. Measured
  // without gloss (no Saunderson correction needed).
  'Phthalo Blue (GS)': [['PB15-3_solid_FOGRA51', 'substrate-paper-PC1_FOGRA51'], null, 'Process cyan ink film over paper (FOGRA51)', 'film'],
  'French Ultramarine': ['PB29_masstone_Berns2016', 'PB29_tint020_RIT-Okumura', 'Golden acrylic'],
  'Dioxazine Violet': ['PV23_masstone_Berns2016', 'PV23_tint020_RIT-Okumura', 'Golden acrylic'],
  'Quinacridone Magenta': ['PR122_masstone_Berns2016', 'PR122_tint010_RIT-Okumura', 'Golden acrylic'],
  'Quinacridone Rose': ['PV19_masstone_Berns2016', 'PV19_tint035_Berns2016', 'Golden Quinacridone Red (PV19), acrylic'],
  'Pyrrole Rubine': ['PR264_masstone_CHSOS-modern', null, 'Kremer pigment in acrylic on card, thin'],
  'Pyrrole Scarlet': ['PR255_masstone_CHSOS-modern', null, 'Kremer pigment in acrylic on card, thin'],
  'Perylene Maroon': ['PR179_masstone_CHSOS-modern', null, 'Kremer pigment in acrylic on card, thin'],
  'Isoindolinone Yellow': ['PY110_masstone_CHSOS-modern', null, 'Kremer pigment in acrylic on card, thin'],
  'Bismuth Vanadate Yellow': ['PY184_masstone_Berns2016', 'PY184_tint054_Berns2016', 'Golden acrylic'],
  'Indian Red': ['PR101_masstone_RIT-Okumura', 'PR101_tint020_RIT-Okumura', 'Golden Red Oxide (opaque PR101), acrylic'],
  'Raw Umber': ['PBr7_masstone_RIT-Okumura', 'PBr7_tint020_RIT-Okumura', 'Golden acrylic'],
  'Titanium Buff': ['PW6-1_TitanBuff_masstone_RIT-Okumura', 'PW6-1_TitanBuff_tint020_RIT-Okumura', 'Golden Titan Buff, acrylic'],
  'White Gouache': ['PW6_masstone_Berns2016', null, 'Golden Titanium White, acrylic'],
};

async function band(file) {
  const rows = (await readFile(new URL(`${file}.csv`, DIR), 'utf8')).trim().split('\n')
    .map(l => l.split(',').map(Number)).filter(([nm, r]) => Number.isFinite(nm) && Number.isFinite(r));
  return BANDS.map(b => {
    const inBand = rows.filter(([nm]) => nm >= b - 10 && nm <= b + 10);
    return +(inBand.reduce((a, [, r]) => a + r, 0) / inBand.length).toFixed(4);
  });
}

const out = {};
for (const [name, [m, t, note, kind]] of Object.entries(PICK)) {
  if (kind === 'film') {
    // A film over paper: transmittance squared = film / paper.
    const [film, paper] = [await band(m[0]), await band(m[1])];
    const T2 = film.map((v, k) => +Math.min(v / paper[k], 1).toFixed(4));
    out[name] = { film: T2, masstone: null, tint: null, source: `${m[0]} / ${m[1]}: ${note}` };
    continue;
  }
  out[name] = { masstone: await band(m), tint: t ? await band(t) : null, source: `${m}${t ? ` + ${t}` : ''}: ${note}` };
}
await writeFile(new URL('../src/spectra-data.js', import.meta.url),
`// Generated by tools/spectra.mjs from notes/spectra (published measurements;
// see notes/spectra/sources.md). 16 bands, 400-700 nm. Don't edit by hand.
export const MEASURED = {
${Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: {\n${v.film ? `    film: ${JSON.stringify(v.film)},\n` : ''}    masstone: ${JSON.stringify(v.masstone)},\n    tint: ${JSON.stringify(v.tint)},\n    source: ${JSON.stringify(v.source)},\n  },`).join('\n')}
};
`);
console.log(`wrote ${Object.keys(out).length} pigments`);
