// Plain-language notes for every knob in params.js, for the painter.
// tier: 'studio' (adjusted while painting), 'lab' (laws of the medium and
// calibration), 'dev' (performance and debugging). Same order as PARAMS.

export const KNOB_DOCS = {
  // --- Flow ---
  activeTiles: { tier: 'dev', doc: 'Performance only: 1 skips dry, untouched patches of the sheet each step. 0 simulates the whole sheet every step (slower, same painting).' },
  dt: { tier: 'dev', doc: 'Size of each simulation step. Larger runs the physics faster per step but less stably (puddles can wobble or blow up); it also scales every rate in the sim.' },
  simSpeed: { tier: 'dev', doc: 'Simulation steps per real second. Higher makes water flow and dry faster in real time, if the GPU keeps up; 0 freezes the painting.' },
  gravity: { tier: 'lab', doc: 'How hard deeper water pushes toward shallower water. More: puddles level out and runs travel faster; also how strongly board tilt and paper texture steer water.' },
  viscosity: { tier: 'lab', doc: 'Internal thickness of the water: more smooths out the flow so neighbouring water moves together, damping swirls and ripples.' },
  drag: { tier: 'lab', doc: 'Friction of the paper on moving water. More: washes creep and stay where laid; less: water slides and runs freely.' },
  dragMaxBoost: { tier: 'lab', doc: 'Cap on how much extra friction thin films get over deep water (1 = none). More: a thin damp wash sticks to the paper while puddles still flow.' },
  dragDepth: { tier: 'lab', doc: 'Water depth below which thin-film friction starts growing. More: fairly deep washes already count as thin and stick; less: only a bare film sticks.' },
  paperRelief: { tier: 'lab', doc: "How much the paper's tooth (hills and valleys) steers surface water. More: water gathers in the valleys and follows the texture." },
  tiltX: { tier: 'studio', doc: 'Tilts the board left/right: positive runs water (and a bead of paint) to the right, negative to the left. 0 = flat.' },
  tiltY: { tier: 'studio', doc: 'Tilts the board toward/away from you: positive runs water down the sheet, negative up. 0 = flat. Use for graded washes and runs.' },
  surfaceTension: { tier: 'lab', doc: 'Surface tension of the water: more smooths a wash over the tooth, rounding bumps and filling dips in the film. Capped automatically in deep puddles.' },
  capSuction: { tier: 'lab', doc: 'Meniscus pull toward thin water: more feeds a drying wash from its thick middle out to its thinning rim, so the edge recedes smoothly instead of in tide lines. 0 = off.' },
  suctionDepth: { tier: 'lab', doc: 'Depth scale for thin-film suction: larger means deeper water still counts as thin and gets pulled toward. Only matters when thin-film suction is above 0.' },
  pinning: { tier: 'lab', doc: 'How firmly a wet edge holds on dry paper (contact-angle hysteresis). More: crisp edges that only break out under a big pool. Also caps how much a wet-in-wet charge can flood.' },
  edgeDamp: { tier: 'lab', doc: 'The sheet\'s edge holds water like a wet edge, but a closed wall also bounced it straight back in. This slows flow toward and away from the edge within about 6 mm of it (flow along the edge is untouched). 0: a perfectly reflecting wall.' },
  edgePull: { tier: 'lab', doc: 'Draws water, and the pigment in it, outward toward the rim of a wet area as it dries (Curtis\'s edge darkening). More: darker, harder dried edges on washes.' },

  // --- Paper & drying ---
  evaporation: { tier: 'lab', doc: 'How fast standing water evaporates off the surface. More: washes lose their shine and dry sooner, leaving less time to work wet-in-wet.' },
  edgeEvaporation: { tier: 'lab', doc: 'Extra evaporation near a wash\'s rim, where the water is thin and exposed. More: edges dry first, which feeds edge darkening and blooms.' },
  sizing: { tier: 'lab', doc: 'Gelatine sizing of the paper (0 unsized to 1 hard-sized). More: water soaks in slower and evenly and wicks less (crisp edges); less: fast, blotchy soaking and feathered edges like washi.' },
  absorption: { tier: 'lab', doc: 'How fast the paper drinks surface water into its fibres (reduced by sizing). More: washes sink in quickly and lose their free-flowing time.' },
  capacityMin: { tier: 'lab', doc: 'How much water the paper can hold at the peaks of its tooth. More: a thirstier sheet overall; with capacity (valleys) sets how unevenly soaking follows texture.' },
  capacityMax: { tier: 'lab', doc: 'How much water the paper can hold in the valleys of its tooth. More: a thirstier sheet. Also the most the mist can dampen the paper to.' },
  capillarySpread: { tier: 'lab', doc: 'How fast water creeps sideways through the fibres (reduced by sizing). More: damp halos spread past a wash\'s edge and edges feather.' },
  pigmentWick: { tier: 'lab', doc: 'Water soaking sideways through the fibres carries fine pigment with it (by each pigment\'s wick rating), out past the wet edge into damp paper. Unsized papers like washi feather most; sized cotton softens its rims a little. 0: pigment stops at the surface water\'s edge.' },
  fibreSettle: { tier: 'lab', doc: 'Pigment carried into damp paper beyond the surface water settles this share per step while the fibres are wet, so it travels on a little: lower, it feathers further; 1: it settles at once (a hard rim where it arrives).' },
  capillaryMin: { tier: 'lab', doc: 'How damp fibres must be before they wick sideways. More: only well-soaked paper spreads its water; less: even slightly damp paper wicks.' },
  dampThreshold: { tier: 'lab', doc: 'How damp the paper must be for a wash to flow onto it. More: water stays put on barely damp paper. Also where dry-brush stops working and when paint counts as dry.' },
  dryingPace: { tier: 'studio', doc: 'How fast the paper dries through its stages (soaked, shiny, satin, moist, damp, dry). 1: about 6x faster than real paper in a studio; 0.17: real time, for when you want time to work in a stage. The dryer multiplies it. Skip ahead jumps forward instead.' },
  paperEvaporation: { tier: 'lab', doc: 'How fast the paper itself dries once the shine is gone (a share of the water left in the fibres, so it slows as it goes): sets how long the paper stays moist and then damp. More: damp paper returns to bone dry quickly, so late strokes get hard edges sooner.' },
  wEps: { tier: 'dev', doc: 'Numerical threshold: water thinner than this counts as dry surface. Mostly a stability setting; raising it makes washes lose their shine and stop flowing earlier.' },
  dryerStrength: { tier: 'studio', doc: 'How much faster everything dries while the hair dryer is on (multiplies both evaporation rates). More: a stronger, hotter dryer.' },

  // --- Pigment ---
  mixing: { tier: 'lab', doc: 'On/off (0/1) for paint spreading within water: diffusion, the Marangoni burst and flocculation. At 0 pigment moves only with flowing water (magnets still work).' },
  marangoniContrast: { tier: 'lab', doc: 'How much the Marangoni burst needs paint meeting much clearer water. More: blooms and bursts happen only at strong paint/clear-water boundaries, not within a wash.' },
  marangoni: { tier: 'lab', doc: 'How strongly paint shoots out into clearer water (Marangoni flow): the feathery burst of a charged brush into a wet wash, and blooms. Negative pulls paint into clumps.' },
  pigmentDiffusion: { tier: 'lab', doc: 'Gentle, steady spreading of pigment through still water. More: soft, blurred wet-in-wet mixes; scaled by each pigment\'s mobility rating.' },
  mixEdgeLo: { tier: 'lab', doc: 'Near a wash\'s edge pigment spreading is switched off, so it can\'t undo edge darkening. Lower bound of that fade (how edge-ish a spot must be to get none).' },
  mixEdgeHi: { tier: 'lab', doc: 'Upper bound of the edge fade: spots this far inside a wash spread pigment fully. Raise both edge values to protect a wider rim from mixing.' },
  jamLo: { tier: 'lab', doc: 'Pigment-to-water ratio at which paint starts behaving like paste and stops being carried along by water. Lower: thick paint stays put sooner.' },
  jamHi: { tier: 'lab', doc: 'Ratio at which paint is fully jammed and water flows past without moving it. Prevents dark contour lines from pigment piling at drying edges.' },
  density: { tier: 'lab', doc: 'Scales every pigment\'s own density (settling) rating. More: pigment drops out of the water faster, especially as it thins at drying edges, and also redissolves faster.' },
  staining: { tier: 'lab', doc: 'Scales every pigment\'s own staining rating; 1 = as calibrated. More: settled paint grips the fibres and resists rewetting, lifting and mask peel.' },
  granulation: { tier: 'lab', doc: 'Scales every pigment\'s own granulation rating. More: settling pigment gathers in the paper\'s valleys for a speckled, sedimentary texture.' },
  rewetLift: { tier: 'lab', doc: 'How readily the thin, fibre-bound layer of paint that has dried and set redissolves under a new wash, as a fraction of fresh. More: glazes disturb earlier layers.' },
  stainCapacity: { tier: 'lab', doc: 'How much pigment the fibres themselves can grip. Paint up to this amount lifts per its staining; anything piled above lifts freely, so thick paint reactivates.' },
  thickRewet: { tier: 'lab', doc: 'How readily thick dried paint (piled above the fibres\' grip) redissolves when rewetted, as a fraction of fresh. More: heavy passages melt under a wet brush.' },
  soakTime: { tier: 'lab', doc: 'Dried, gum-set paint stays put under a quick glaze: it only starts to rewet once standing water has sat on it about this long (ramping up gradually; damp paper alone doesn\'t count). 0: it rewets the moment water touches it.' },
  thickLo: { tier: 'lab', doc: 'Paint piled thicker than this (an oversaturated line) starts to rewet under a wet brush without soaking first: loose pigment sits above what the gum holds down. Thin glaze-like layers still need soaking or scrubbing.' },
  thickHi: { tier: 'lab', doc: 'Thickness at which piled paint rewets as freely as fresh (no soaking needed).' },
  soakRewet: { tier: 'lab', doc: 'Dried paint whose gum has softened under standing water mostly stays where it is unless something works at it: left alone it comes back up at this fraction of the rate a scrubbing brush gets. 1: soaking alone lifts it as freely as scrubbing.' },
  agitation: { tier: 'lab', doc: 'How much a brush working wet paper loosens the dried paint under it while it passes, scaled by the brush\'s firmness: a soft brush glazes without disturbing the layer below, a firm one lifts it.' },
  scrubRewet: { tier: 'lab', doc: 'A brush working over wet, dried paint softens its gum this many times faster than soaking alone (scaled by pressure). Scrub to reactivate; a single glaze pass barely disturbs it.' },
  packLo: { tier: 'lab', doc: 'Pigment piling up at a wash\'s pinned edge packs into a ring: from this much pigment in a spot, less more can be carried into it, so the ring widens inward instead of darkening to a hairline.' },
  packHi: { tier: 'lab', doc: 'Pigment in a spot at which nothing more is carried in (the edge ring\'s darkest). Higher: darker, thinner rims.' },
  bindTime: { tier: 'lab', doc: 'Seconds for the gum arabic to set once paint is dry. Rewetted sooner, paint dissolves freely; after this it has set and rewets per the rewet settings.' },

  // --- Fixative ---
  fixRewet: { tier: 'lab', doc: 'How readily fixed paint redissolves under a new wash, as a fraction of ordinary dried paint. 0 = fixed layers never move.' },
  fixLift: { tier: 'lab', doc: 'How easily fixed paint lifts (scrubbing, blotting, mask peel), as a fraction of unfixed. Less: fixed layers survive a thirsty brush.' },
  fixSeal: { tier: 'lab', doc: 'How much fixative seals the paper: later washes soak in and wick more slowly, staying wet and workable longer. 1 = fully sealed.' },
  fixTooth: { tier: 'lab', doc: 'How much each fixative spray fills the paper\'s tooth, flattening it. More: less granulation and dry-brush texture afterwards.' },
  fixDeepen: { tier: 'lab', doc: 'How much fixative darkens and richens fixed paint, undoing the lightening watercolour shows as it dries. Display only.' },

  // --- Pigment (flocculation) ---
  flocculation: { tier: 'lab', doc: 'Scales every pigment\'s own flocculation rating. More: flocculating pigments (ultramarine above all) clump into mottles while wet. Same effect as floc clumping speed.' },
  flocTogether: { tier: 'lab', doc: 'How much mixed flocculating pigments clump together (1: one shared mottle, e.g. grey flocs) versus separately (0: blue and orange specks).' },
  flocDrift: { tier: 'lab', doc: 'How fast flocculating pigment gathers into clumps while wet. More: stronger mottling in the time the wash stays wet. Multiplies with flocculation.' },
  flocScale: { tier: 'lab', doc: 'Size of the flocculation mottles in mm. Larger: broader, cloudier clumps; smaller: fine grain.' },

  // --- Magnets ---
  magnetism: { tier: 'studio', doc: 'Strength of magnets under the paper on magnetic pigments (per each pigment\'s magnetic rating, e.g. Mars black). Negative pushes pigment away instead.' },
  magnetDepth: { tier: 'studio', doc: 'How far below the paper the magnets sit, in mm. Deeper: a broader, softer pull; shallower: tight, sharp gathering right over the magnet.' },

  // --- Pigment (settling) ---
  valleyFill: { tier: 'lab', doc: 'How quickly settled pigment fills the paper\'s valleys. More: granulation fades as paint gets dense, so pale washes speckle and masstone goes flat.' },
  settleDepth: { tier: 'lab', doc: 'Scales settling by how thin the water is. More: pigment drops out sooner overall and piles at thinning, drying edges; less: stays suspended longer.' },

  // --- Brush ---
  brushRadius: { tier: 'studio', doc: 'Brush size (radius in cells) at full pressure. The stroke narrows with lighter touch per taper.' },
  brushSoftness: { tier: 'studio', doc: 'How soft the edge of each brush mark is: 0 a hard-edged stamp, 1 fades from the centre out.' },
  brushWater: { tier: 'studio', doc: 'How much water the brush lays down: the depth it tops a wash up to. More: juicy, flowing washes; less: stiffer, drier paint.' },
  brushPigment: { tier: 'studio', doc: 'Paint strength: pigment per water in the brush. More: darker, more concentrated mixes; less: paler tints.' },
  brushRate: { tier: 'studio', doc: 'How quickly the brush releases its load onto the paper. More: a single pass reaches full strength; less: builds up over repeated passes.' },
  brushCharge: { tier: 'lab', doc: 'Extra burst of water a freshly loaded brush releases when touching an already wet wash. More: stronger wet-in-wet blooms and bursts.' },
  chargeDuration: { tier: 'lab', doc: 'How long (s) after touchdown the wet-in-wet charge lasts before the brush has spent it. Longer: dragging through a wash keeps flooding it.' },
  brushShape: { tier: 'studio', doc: 'Brush shape: 0 round, 1 flat (a chisel-edged rectangle swept along the stroke).' },
  flatAngle: { tier: 'studio', doc: 'Angle of the flat brush in degrees (R or scroll to turn). Pulled broadside it lays a wide band; along its edge, a thin line.' },
  flatThickness: { tier: 'studio', doc: 'Thickness of the flat brush\'s chisel edge as a fraction of its width. Less: a sharper, thinner edge line.' },
  lingerRate: { tier: 'lab', doc: 'How fast paint builds up while the brush rests in one place. More: a held brush blots out a darker, wetter spot.' },
  dabDelay: { tier: 'lab', doc: 'Seconds the brush must be held still before it lays a dab. Stops an accidental dot at the start of every stroke.' },
  startWet: { tier: 'lab', doc: 'A freshly loaded brush lets out more water (and paint) at the start of a stroke, fading over its first few brush-widths. Without it a stroke\'s start came out thinner, dried first and took an edge as the wetter paint ran back in. 0: an even level all along.' },
  brushFirmness: { tier: 'lab', doc: 'How stiff the brush is, so how hard it scrubs dried paint as it passes: a soft squirrel mop glazes without disturbing the layer below, a firm bristle flat scrubs it up. Working a spot longer scrubs more.' },
  brushDrag: { tier: 'lab', doc: 'How much the hairs push wet paint along with them. More: dragging through wet paint smears and shoves it in the stroke direction.' },
  brushPickup: { tier: 'lab', doc: 'How much the paint and clear-water brushes trade pigment with wet paint they cross: picks up from strong areas, lays down in weak. More: smearing and softening.' },
  carryVolume: { tier: 'lab', doc: 'How much water the picked-up paint is diluted in, relative to the brush tip. More: carried colour comes off weaker when it\'s laid down elsewhere.' },
  carryKeep: { tier: 'lab', doc: 'Fraction of picked-up colour the brush still holds at the next stroke (rinsing). 0: clean each stroke; 1: never rinsed, colour gets dragged around.' },
  brushDose: { tier: 'lab', doc: 'How much paint each spot gets as the brush passes over it, at any speed. More: fuller strokes; less: lighter strokes.' },
  taperMin: { tier: 'studio', doc: 'Stroke width at the lightest touch, as a fraction of full size. Less: fine tapered tips; 1: same width at any pressure.' },
  brushCapacity: { tier: 'lab', doc: 'Water brush only: how much it paints before its reservoir runs dry (squeeze to refill). 0 = endless. The dip brush uses Wetness instead.' },
  mouseTouch: { tier: 'studio', doc: 'Mouse/trackpad pressure (Z or Option lighter, X heavier). Lighter: thinner strokes, and dry-brush skipping if the brush is drying.' },
  touchRate: { tier: 'studio', doc: 'How fast holding Z/Option/X changes the mouse touch, per second. More: quicker response.' },
  dipLoad: { tier: 'studio', doc: 'Wetness: how full the dip brush is each stroke. Lower: less water laid, thicker paint, dry-brush skipping, and a thirstier brush for lifting. With the clean brush it sets what the brush does: full lays water, turned down it softens and drinks a little, right down it is thirsty and lifts.' },
  dryBelow: { tier: 'lab', doc: 'How empty the brush must be before it starts skipping over the tooth (dry-brush). Higher: dry-brush kicks in with a fuller brush.' },
  speedSkim: { tier: 'lab', doc: 'How much a fast stroke skims over the tooth when the brush is drying. More: quick flicks with a dry brush give broken, sparkly marks.' },
  touchdownEase: { tier: 'lab', doc: 'Mouse only: seconds for a stroke to go from a light touch to full pressure after touchdown. More: softer, tapered starts.' },
  emptyLevel: { tier: 'lab', doc: 'Fraction of its water the brush still lays down when empty. More: an emptying brush stays wetter; less: it runs properly dry.' },
  dabSize: { tier: 'lab', doc: 'Water brush only: how much painting one dab of pigment lasts. More: a dab goes further before the colour runs out.' },
  squeezeRate: { tier: 'lab', doc: 'Water brush only: how fast squeezing (Q) refills its water, per second.' },
  thicken: { tier: 'lab', doc: 'Dip brush only: how much stronger the paint gets as the brush has less water (lower Wetness). 0: same strength however dry.' },
  skipAmount: { tier: 'lab', doc: 'How much of the tooth a dry, light brush skips on dry paper. More: only the peaks catch paint, broken sparkly dry-brush; less: solid marks.' },
  mistRadius: { tier: 'studio', doc: 'Mist: how wide the spray reaches (cells). Dense in the middle, thinning out.' },
  mistWater: { tier: 'studio', doc: 'Mist: how much water each droplet leaves. More: bigger beads that can merge into a wet film.' },
  mistDensity: { tier: 'studio', doc: 'Mist: how many droplets land per pass. More: fuller coverage.' },
  mistDamp: { tier: 'lab', doc: 'Mist: how much the spray dampens the paper itself, so later strokes soften and melt together instead of drying with hard edges.' },
  pencilRadius: { tier: 'studio', doc: 'Width of the pencil line: 2.5 cells is a 0.5 mm mechanical pencil.' },
  pencilDark: { tier: 'studio', doc: 'How much graphite each pass leaves, from a hard lead (light, catching only the tooth\'s peaks) to a soft one (dark). Pressing harder also pushes it into the valleys.' },
  eraserRadius: { tier: 'studio', doc: 'Size of the eraser.' },
  eraseRate: { tier: 'lab', doc: 'How much of the graphite under it one eraser pass takes. Graphite that paint has been laid over since is sealed in and can\'t be erased.' },
  maskTear: { tier: 'lab', doc: 'How much dried paint peeling off masking fluid tears away with it. More: more lost; lifts non-staining pigments most, phthalos barely.' },
  blotRadius: { tier: 'studio', doc: 'Blot: size of the crumpled paper towel wad (cells).' },
  blotScale: { tier: 'studio', doc: 'Blot: size of the towel\'s creases in mm. Larger: broader, cloudier mottling; smaller: finer texture.' },
  blotRate: { tier: 'studio', doc: 'Blot: how much water and paint each press soaks up where a crease touches. More: cleaner, whiter blotted areas.' },
  liftWater: { tier: 'lab', doc: 'Lift: how much wet paint and water a thirsty brush soaks up. Lower Wetness is thirstier; at full Wetness it barely lifts.' },
  liftLeaves: { tier: 'lab', doc: 'Lift: water always left on wet paper after lifting, so the spot stays joined to the wash instead of drying to a hard-edged ring.' },
  liftUnset: { tier: 'lab', doc: 'How much more easily Lift and blotting take paint whose gum has not set yet (paper still damp) than dried paint. Lifting while damp gives soft lights; once dry, the same lift barely moves it.' },
  liftDry: { tier: 'lab', doc: 'How easily scrubbing and blotting lift settled/dried paint, divided by each pigment\'s staining. More: dried non-staining paint lifts readily.' },
  liftStrength: { tier: 'studio', doc: 'Lift: how hard the lifting brush scrubs. More: removes wet paint and dried paint faster.' },

  // --- Render ---
  undoDepth: { tier: 'dev', doc: 'How many full snapshots of the sheet undo keeps on the GPU (about 175 MB each). Undo goes back past them by replaying the logged painting from the nearest one, so more snapshots mean faster undo far back, not a longer history.' },
  thickness: { tier: 'lab', doc: 'How dark and saturated a given amount of pigment looks (the paint film\'s optical thickness). More: the same paint reads stronger. Display only.' },
  wetDarken: { tier: 'lab', doc: 'How much standing water darkens the paint beneath it (up to 30%), so wet paint looks deeper than it dries. Display only.' },
  dampDarken: { tier: 'lab', doc: 'How much damp paper (no standing water) looks darker, up to 15%, so you can see where it hasn\'t dried. Display only.' },
  paperShade: { tier: 'lab', doc: 'How visible the paper\'s texture is as shading on its colour. Display only; not used on a toned ground.' },
  spectral: { tier: 'lab', doc: 'Colour model: 1 mixes paints per wavelength (truer mixes, e.g. blue + yellow greens), 0 per red/green/blue channel (faster). Display only.' },
  suspendedWeight: { tier: 'dev', doc: 'How much pigment still floating in wet water shows (1 = true to life, 0 = hide it, show only settled paint). A diagnostic view.' },
};
