// Generated by tools/spectra.mjs from data/spectra (published measurements;
// see data/spectra/sources.md). 16 bands, 400-700 nm. Don't edit by hand.
export const MEASURED = {
  "Phthalo Green": {
    masstone: [0.0495,0.0498,0.0516,0.0589,0.0761,0.0816,0.0603,0.0437,0.0384,0.0371,0.0373,0.0393,0.0419,0.0452,0.0473,0.0474],
    tint: [0.152,0.1945,0.2354,0.3268,0.474,0.5475,0.4965,0.3941,0.2818,0.1869,0.1208,0.0933,0.0873,0.0891,0.0995,0.1095],
    source: "PG7_masstone_Berns2016 + PG7_tint040_RIT-Okumura: Golden acrylic",
  },
  "Phthalo Blue (GS)": {
    film: [0.479,0.5454,0.662,0.7816,0.7914,0.7218,0.5703,0.3636,0.1752,0.0782,0.0494,0.0416,0.0461,0.0608,0.0647,0.0514],
    masstone: null,
    tint: null,
    source: "PB15-3_solid_FOGRA51 / substrate-paper-PC1_FOGRA51: Process cyan ink film over paper (FOGRA51)",
  },
  "French Ultramarine": {
    masstone: [0.0704,0.1067,0.1541,0.1386,0.0684,0.0392,0.036,0.0354,0.0349,0.0347,0.0348,0.035,0.0353,0.0358,0.0369,0.0396],
    tint: [0.4134,0.6937,0.752,0.7281,0.6319,0.4986,0.3812,0.3006,0.2527,0.2262,0.2153,0.2165,0.2304,0.2611,0.3163,0.3967],
    source: "PB29_masstone_Berns2016 + PB29_tint040_RIT-Okumura: Golden acrylic",
  },
  "Dioxazine Violet": {
    masstone: [0.0483,0.0465,0.0446,0.0428,0.0414,0.0407,0.0419,0.0444,0.0467,0.0501,0.0497,0.0483,0.0529,0.0635,0.0849,0.1326],
    tint: [0.2691,0.3823,0.4004,0.3607,0.2785,0.1881,0.1307,0.1094,0.1064,0.12,0.1487,0.1449,0.168,0.2758,0.4326,0.5767],
    source: "PV23_masstone_Berns2016 + PV23_tint040_RIT-Okumura: Golden acrylic",
  },
  "Quinacridone Magenta": {
    masstone: [0.0929,0.0834,0.0685,0.0564,0.0493,0.0456,0.0441,0.0447,0.0468,0.0547,0.0866,0.2115,0.4055,0.5407,0.6095,0.6543],
    tint: [0.3376,0.4807,0.452,0.3849,0.3127,0.2477,0.1883,0.1569,0.1643,0.2456,0.4568,0.6612,0.7745,0.8192,0.8378,0.848],
    source: "PR122_masstone_Berns2016 + PR122_tint040_RIT-Okumura: Golden acrylic",
  },
  "Quinacridone Rose": {
    masstone: [0.1011,0.0862,0.0647,0.0524,0.0475,0.0462,0.0468,0.0478,0.0531,0.0841,0.1973,0.3946,0.529,0.5965,0.6381,0.6744],
    tint: [0.369,0.4904,0.4319,0.3512,0.2818,0.2374,0.2019,0.1948,0.1933,0.326,0.5847,0.7733,0.8342,0.8557,0.8676,0.8774],
    source: "PV19_masstone_Berns2016 + PV19_tint035_Berns2016: Golden Quinacridone Red (PV19), acrylic",
  },
  "Pyrrole Rubine": {
    masstone: [0.1196,0.0811,0.0604,0.0493,0.0442,0.041,0.0393,0.0386,0.0388,0.0415,0.0513,0.1525,0.4358,0.6155,0.6531,0.6667],
    tint: null,
    source: "PR264_masstone_CHSOS-modern: Kremer pigment in acrylic on card, thin",
  },
  "Pyrrole Scarlet": {
    masstone: [0.1105,0.081,0.0638,0.0545,0.0488,0.0453,0.0423,0.0432,0.0508,0.1141,0.286,0.4964,0.595,0.6094,0.6039,0.5996],
    tint: null,
    source: "PR255_masstone_CHSOS-modern: Kremer pigment in acrylic on card, thin",
  },
  "Perylene Maroon": {
    masstone: [0.112,0.0789,0.0582,0.0485,0.0441,0.0422,0.0402,0.0393,0.0378,0.0404,0.0498,0.0813,0.1416,0.1915,0.2183,0.2351],
    tint: null,
    source: "PR179_masstone_CHSOS-modern: Kremer pigment in acrylic on card, thin",
  },
  "Isoindolinone Yellow": {
    masstone: [0.1237,0.0903,0.0704,0.0624,0.0602,0.0633,0.0878,0.2026,0.4424,0.6645,0.7885,0.8527,0.8856,0.8997,0.9042,0.9079],
    tint: null,
    source: "PY110_masstone_CHSOS-modern: Kremer pigment in acrylic on card, thin",
  },
  "Bismuth Vanadate Yellow": {
    masstone: [0.0554,0.0551,0.058,0.0821,0.2094,0.4783,0.7358,0.8743,0.9238,0.9388,0.9441,0.9467,0.9489,0.9512,0.9529,0.9538],
    tint: [0.1538,0.1645,0.163,0.1949,0.3503,0.6166,0.8222,0.9097,0.9304,0.9351,0.9363,0.9366,0.9381,0.9401,0.9414,0.9421],
    source: "PY184_masstone_Berns2016 + PY184_tint054_Berns2016: Golden acrylic",
  },
  "Indian Red": {
    masstone: [0.0444,0.0446,0.0445,0.0444,0.0449,0.0457,0.0473,0.0522,0.0721,0.1308,0.2094,0.2572,0.2792,0.2988,0.326,0.3613],
    tint: [0.1763,0.2026,0.1974,0.1921,0.188,0.1852,0.1836,0.1887,0.223,0.3137,0.4179,0.4747,0.4997,0.5203,0.546,0.5775],
    source: "PR101_masstone_RIT-Okumura + PR101_tint040_RIT-Okumura: Golden Red Oxide (opaque PR101), acrylic",
  },
  "Raw Umber": {
    masstone: [0.0417,0.0418,0.0419,0.0419,0.0418,0.0421,0.0423,0.0426,0.0428,0.0429,0.0431,0.0428,0.0426,0.0426,0.0427,0.0428],
    tint: [0.1733,0.2069,0.2126,0.2144,0.2148,0.2167,0.2197,0.2232,0.2267,0.2289,0.2294,0.2287,0.2269,0.2246,0.2224,0.2209],
    source: "PBr7_masstone_RIT-Okumura + PBr7_tint040_RIT-Okumura: Golden acrylic",
  },
  "Titanium Buff": {
    masstone: [0.2363,0.3578,0.4324,0.4879,0.524,0.5521,0.5834,0.6152,0.6451,0.6729,0.6957,0.7123,0.7265,0.7356,0.7403,0.7442],
    tint: [0.3508,0.5594,0.6332,0.674,0.6996,0.7182,0.738,0.7578,0.777,0.7932,0.8058,0.8141,0.8203,0.8217,0.8212,0.8205],
    source: "PW6-1_TitanBuff_masstone_RIT-Okumura + PW6-1_TitanBuff_tint040_RIT-Okumura: Golden Titan Buff, acrylic",
  },
  "White Gouache": {
    masstone: [0.4894,0.8615,0.9584,0.9621,0.9601,0.9585,0.9572,0.9563,0.9542,0.9524,0.9502,0.9491,0.9496,0.9507,0.9503,0.9498],
    tint: null,
    source: "PW6_masstone_Berns2016: Golden Titanium White, acrylic",
  },
};
